// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JomSibu.Shared.Models;

public partial class BudgetStatusesTable
{
    public int Id { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<HotelsTable> HotelsTables { get; set; } = new List<HotelsTable>();

    public virtual ICollection<UserDetailsTable> UserDetailsTables { get; set; } = new List<UserDetailsTable>();
}