// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JomSibu.Shared.Models;

public partial class HotelsTable
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int? BudgetStatusId { get; set; }

    public virtual BudgetStatusesTable BudgetStatus { get; set; }

    public virtual ICollection<UserHotelsTable> UserHotelsTables { get; set; } = new List<UserHotelsTable>();
}