// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JomSibu.Shared.Models;

public partial class PreferencesTable
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<LocationPreferencesTable> LocationPreferencesTables { get; set; } = new List<LocationPreferencesTable>();

    public virtual ICollection<UserPreferencesTable> UserPreferencesTables { get; set; } = new List<UserPreferencesTable>();
}