// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JomSibu.Shared.Models;

public partial class UserDetailsTable
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public int? IsHalal { get; set; }

    public int? IsVegetarian { get; set; }

    public int? IsDeleted { get; set; }

    public string ImagePath { get; set; }

    public int? BudgetStatusId { get; set; }

    public string AspNetUserId { get; set; }

    public DateTime? DateJoined { get; set; }

    public int? UserRoleId { get; set; }

    public virtual BudgetStatusesTable BudgetStatus { get; set; }

    public virtual ICollection<UserHotelsTable> UserHotelsTables { get; set; } = new List<UserHotelsTable>();

    public virtual ICollection<UserPreferencesTable> UserPreferencesTables { get; set; } = new List<UserPreferencesTable>();

    public virtual ICollection<UserRoutesTable> UserRoutesTables { get; set; } = new List<UserRoutesTable>();

    public virtual ICollection<UserVouchersTable> UserVouchersTables { get; set; } = new List<UserVouchersTable>();
}