// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JomSibu.Shared.Models;

public partial class UserHotelsTable
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? HotelId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? IsDeleted { get; set; }

    public virtual HotelsTable Hotel { get; set; }

    public virtual UserDetailsTable User { get; set; }
}