// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JomSibu.Shared.Models;

public partial class VouchersTable
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ExpiryDate { get; set; }

    public string ImagePath { get; set; }

    public virtual ICollection<UserVouchersTable> UserVouchersTables { get; set; } = new List<UserVouchersTable>();
}